### ISSUE TITLE
Working for v2?

### ISSUE THREAD

**Issue by thundergreen** [asphalter/xiaomi_vacuum#1]
Was wondering if this method also works for v2 and if someone could report back

**Comment by asphalter** [comment]
Unfortunately I don't have a v2 vacuum to test this method on, but most likely it will work, because the software it's absolutely the same. Mopping features and carpet detection are simply disabled on the v1.

**Comment by ewilly** [comment]
Awesome work !!! And es it's well working with v2 !

**Comment by thundergreen** [comment]
Works...closed
